spring.application.name=demo

server.port=8080

spring.datasource.url=jdbc:mysql://circle-the-city-db.cb2m68i2oave.us-west-2.rds.amazonaws.com:3306/circle_the_city
spring.datasource.username=admin
spring.datasource.password=CircleTheCity411
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false